version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add your environment variables here or in a .env file
      # - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      # - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      # - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      # - NEXTAUTH_URL=${NEXTAUTH_URL}
    volumes:
      - ./.env.local:/app/.env.local:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
