import type { Metadata } from "next";
import "./globals.css";

// Using system fonts for better compatibility
const fontSans = {
  variable: '--font-sans',
  className: 'font-sans',
};

const fontMono = {
  variable: '--font-mono',
  className: 'font-mono',
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${fontSans.variable} 
          ${fontMono.variable} 
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
